on:
  pull_request:
    branches:
      - master

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Master
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_SECRET }}
          protocol: ftps
          port: 21
          server-dir: domains/maristelamedeiros.com.br/public_html/
          exclude: | 
            **/wp-content/uploads/**
            **/wp-content/updraft/**
            .htaccess
